# Generated by Django 6.0.6 on 2026-06-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre contacto')),
                ('empresa', models.CharField(blank=True, max_length=160)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('linkedin', models.CharField(blank=True, max_length=200)),
                ('behance', models.CharField(blank=True, max_length=200)),
                ('sitio_web', models.URLField(blank=True)),
                ('fuente', models.CharField(choices=[('instagram', 'Instagram'), ('behance', 'Behance'), ('linkedin', 'LinkedIn'), ('web', 'Web'), ('referido', 'Referido'), ('facebook', 'Facebook'), ('otro', 'Otro')], default='instagram', max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('reunion', 'Reunión Agendada'), ('brief_solicitado', 'Brief Solicitado'), ('brief_recibido', 'Brief Recibido'), ('cotizacion', 'Cotización Enviada'), ('negociacion', 'Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=0, default=0, help_text='Valor potencial del proyecto (CLP)', max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origen', to='clients.client')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-creado'],
            },
        ),
    ]
