# Generated by Django 6.0.6 on 2026-06-10 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('briefs', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('branding', 'Branding'), ('motion', 'Motion Graphics'), ('video', 'Video'), ('redes', 'Redes Sociales'), ('packaging', 'Packaging'), ('editorial', 'Diseño Editorial'), ('web', 'Diseño Web')], default='branding', max_length=20)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('produccion', 'En Producción'), ('feedback', 'Esperando Feedback'), ('correcciones', 'Correcciones'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='planificado', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='briefs.brief')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='clients.client')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('logo', 'Logo'), ('manual', 'Manual de Marca'), ('animacion', 'Animación'), ('reel', 'Reel'), ('video', 'Video'), ('banner', 'Banner'), ('flyer', 'Flyer'), ('presentacion', 'Presentación'), ('mockup', 'Mockups')], default='logo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregables/')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='projects.project')),
            ],
            options={
                'verbose_name': 'entregable',
                'verbose_name_plural': 'entregables',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(choices=[('v1', 'V1'), ('v2', 'V2'), ('v3', 'V3'), ('final', 'Final')], default='v1', max_length=10)),
                ('estado', models.CharField(choices=[('enviada', 'Enviada al cliente'), ('cambios', 'Cambios solicitados'), ('aprobada', 'Aprobada')], default='enviada', max_length=12)),
                ('comentarios', models.TextField(blank=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='projects.deliverable')),
            ],
            options={
                'verbose_name': 'revisión',
                'verbose_name_plural': 'revisiones',
                'ordering': ['-creado'],
            },
        ),
    ]
