# Generated by Django 6.0.6 on 2026-06-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('anticipo', 'Anticipo'), ('saldo', 'Saldo'), ('abono', 'Abono'), ('unico', 'Pago único')], default='anticipo', max_length=15)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('paypal', 'PayPal'), ('otro', 'Otro')], default='transferencia', max_length=15)),
                ('monto', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='projects.project')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
    ]
