# Generated by Django 6.0.6 on 2026-06-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('autor_nombre', models.CharField(blank=True, max_length=160)),
                ('autor_cargo', models.CharField(blank=True, max_length=160)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to='clients.client')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonios', to='projects.project')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'testimonios',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('resultados', models.TextField(blank=True)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('publicado', models.BooleanField(default=False)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caso_estudio', to='projects.project')),
                ('testimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='portfolio.testimonial')),
            ],
            options={
                'verbose_name': 'caso de estudio',
                'verbose_name_plural': 'casos de estudio',
                'ordering': ['-creado'],
            },
        ),
    ]
