# Generated by Django 6.0.6 on 2026-06-10 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_marca', models.CharField(max_length=160)),
                ('rubro', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('recibido', 'Recibido'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('historia', models.TextField(blank=True, verbose_name='historia de marca')),
                ('objetivos', models.TextField(blank=True)),
                ('publico_objetivo', models.TextField(blank=True, verbose_name='público objetivo')),
                ('competencia', models.TextField(blank=True)),
                ('personalidad', models.CharField(blank=True, help_text='Ej: moderna, cercana, premium, disruptiva', max_length=255)),
                ('referencias', models.TextField(blank=True, verbose_name='referencias / inspiraciones')),
                ('colores_deseados', models.CharField(blank=True, max_length=255)),
                ('colores_prohibidos', models.CharField(blank=True, max_length=255)),
                ('tipografias', models.CharField(blank=True, max_length=255)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='briefs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='clients.client')),
            ],
            options={
                'verbose_name': 'brief',
                'verbose_name_plural': 'briefs',
                'ordering': ['-creado'],
            },
        ),
    ]
